apiVersion: apps/v1
kind: Deployment
metadata:
 name: exchange
 namespace: default
spec:
 replicas: 1
 selector:
  matchLabels:
   app: exchange
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxSurge: 1
   maxUnavailable: 0
 template:
  metadata:
   labels:
    app: exchange
   annotations:
    kubernetes.io/change-cause: "v1"
  spec:
   containers:
    - name: exchange
      image: in28min/currency-exchange:0.0.1-RELEASE
      ports:
      - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
 name: ce
spec:
 selector:
  app: exchange
 ports:
  - port: 8000
    targetPort: 8000   
